### ISSUE TITLE
about the other datasets

### ISSUE THREAD

**Issue by yangyang32111** [WendongZh/SPL#8]
First,thanks for your excellent work ! I wonder to know whether I can use other datasets like Cityscapes  to test with your method?Because I have tried,but the result is terrible.

**Comment by WendongZh** [comment]
Nope, the reason is that the distribution of images in Cityscapes dataset is different from those in (such as) Places2 dataset.

I suggest you re-train our model on the Cityscapes dataset or use other inpainting methods which are pre-trained on this dataset, such as" Guidance and Evaluation: Semantic-Aware Image Inpainting for Mixed Scenes", ECCV'20
